name: API status
description: Checks whether the API is active and working on a regular schedule

on:
  schedule:
    - cron: 0 0 * * * # Once a day
  workflow_dispatch:

permissions: {}

jobs:
  api-status:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm clean-install

      - name: Test API
        run: npm run test-api
