name: Publish
description: Publishes the package to the NPM registry when a new release is created

on:
  release:
    types: [released]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout
      id-token: write # Required for npm publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
